import nodemailer from 'nodemailer';

export const sendInquiryNotification = async (messageData) => {
  const emailUser = process.env.EMAIL_USER || process.env.SMTP_USER;
  const emailPass = process.env.EMAIL_PASS || process.env.SMTP_PASS;
  const notificationEmail = process.env.NOTIFICATION_EMAIL || emailUser;

  if (!emailUser || !emailPass) {
    console.log('ℹ️ [Email Service] Skipping email dispatch: EMAIL_USER and EMAIL_PASS environment variables are not set.');
    return { sent: false, reason: 'NOT_CONFIGURED' };
  }

  try {
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT) || 587,
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: emailUser,
        pass: emailPass
      }
    });

    const mailOptions = {
      from: `"Portfolio CMS Alert" <${emailUser}>`,
      to: notificationEmail,
      subject: `🚨 New Lead: ${messageData.subject || 'Portfolio Inquiry'} from ${messageData.name}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333; max-width: 600px; border: 1px solid #e2e8f0; border-radius: 12px;">
          <h2 style="color: #059669; margin-top: 0;">🎉 New Portfolio Contact / Inquiry Received!</h2>
          <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; width: 120px;">Name:</td>
              <td style="padding: 8px 0;">${messageData.name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold;">Email:</td>
              <td style="padding: 8px 0;"><a href="mailto:${messageData.email}">${messageData.email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold;">Subject:</td>
              <td style="padding: 8px 0;">${messageData.subject}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold;">Date:</td>
              <td style="padding: 8px 0;">${new Date(messageData.createdAt || Date.now()).toLocaleString()}</td>
            </tr>
          </table>

          <div style="background-color: #f8fafc; padding: 16px; border-radius: 8px; border-left: 4px solid #059669; white-space: pre-wrap; font-size: 14px;">
            ${messageData.message}
          </div>

          <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
          <p style="font-size: 12px; color: #64748b; margin: 0;">
            This email was automatically generated by your live Portfolio CMS server. Log into your Admin Dashboard at <a href="https://arun-kumar-portfolio.onrender.com/admin/login">arun-kumar-portfolio.onrender.com/admin/login</a> to view and respond to messages.
          </p>
        </div>
      `
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('✅ [Email Service] Notification email sent successfully:', info.messageId);
    return { sent: true, messageId: info.messageId };
  } catch (err) {
    console.error('❌ [Email Service] Failed to send email notification:', err.message);
    return { sent: false, error: err.message };
  }
};
